const hiraganaVocab = [
    {
        level: `N5`,
        lesson: `1`,
        vn: `tôi`,
        hv: `TƯ`,
        kanji: `私`,
        hira: "わたし",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ
        en: `I, me`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `chúng ta, chúng tôi`,
        hv: ``,
        kanji: `私たち`,
        hira: "わたしたち",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ
        en: `we, us`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `ban, anh/chị, ông/bà...`,
        hv: ``,
        kanji: ``,
        hira: "あなた",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ
        en: `you`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `người kia, người đó`,
        hv: `NHÂN`,
        kanji: `あの人`,
        hira: "あのひと",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ
        en: `that person, he/she`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `vị kia`,
        hv: `PHƯƠNG`,
        kanji: `あの方`,
        hira: "あのかた",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (lịch sự)
        en: `that person (polite)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `các bạn, các anh/chị, mọi người, quý vị`,
        hv: `GIAI`,
        kanji: `皆さん`,
        hira: "みなさん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `everyone, all of you`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `anh, chị, ông, bà...`,
        hv: ``,
        kanji: ``,
        hira: `～さん`,
        imgUrl: ``,
        pureKanji: false,
        kind: `suffix`, // hậu tố
        en: `Mr./Ms. (honorific suffix)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `bé (hậu tố thêm vào sau tên bé gái thay cho ～さん)`,
        hv: ``,
        kanji: ``,
        hira: `～ちゃん`,
        imgUrl: ``,
        pureKanji: false,
        kind: `suffix`, // hậu tố
        en: `(cute suffix for girls/children)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `bé (hậu tố thêm vào sau tên bé trai thay cho ～さん)`,
        hv: `QUẢN`,
        kanji: `君`,
        hira: `～くん`,
        imgUrl: ``,
        pureKanji: true,
        kind: `suffix`, // hậu tố
        en: `(suffix for boys/juniors)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `người nước ～`,
        hv: `NHÂN`,
        kanji: `人`,
        hira: `～じん`,
        imgUrl: ``,
        pureKanji: true,
        kind: `suffix`, // hậu tố
        en: `person from ~ (nationality suffix)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `giáo viên (không dùng để nói về nghề nghiệp của mình)`,
        hv: `TIÊN SINH`,
        kanji: `先生`,
        hira: "せんせい",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `teacher`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `giáo viên`,
        hv: `GIÁO SƯ`,
        kanji: `教師`,
        hira: "きょうし",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `teacher, instructor`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `học sinh, sinh viên`,
        hv: `HỌC SINH`,
        kanji: `学生`,
        hira: "がくせい",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `student`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `nhân viên công ty`,
        hv: `HỘI XÃ VIÊN`,
        kanji: `会社員`,
        hira: "かいしゃいん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `company employee`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `nhân viên công ty ～`,
        hv: `XÃ VIÊN`,
        kanji: `社員`,
        hira: `～しゃいん`,
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `~ company employee`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `nhân viên ngân hàng`,
        hv: `NGÂN HÀNH VIÊN`,
        kanji: `銀行員`,
        hira: "ぎんこういん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `bank employee`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `bác sĩ`,
        hv: `Y GIÁ`,
        kanji: `医者`,
        hira: "いしゃ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `doctor`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Nhà nghiên cứu`,
        hv: `NGHIÊN CỨU GIÁ`,
        kanji: `研究者`,
        hira: "けんきゅうしゃ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ nghề nghiệp
        en: `researcher`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `trường đại học`,
        hv: `ĐẠI HỌC`,
        kanji: `大学`,
        hira: "だいがく",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `university, college`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `bệnh viện`,
        hv: `BỆNH VIÊN`,
        kanji: `病院`,
        hira: "びょういん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `hospital`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `điện`,
        hv: `DIỆN KHÍ`,
        kanji: `電気`,
        hira: "でんき",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `electricity, electric light`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `ai (hỏi người nào đó)`,
        hv: `thùy`,
        kanji: `誰`,
        hira: "だれ",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ nghi vấn
        en: `who`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `vị nào (là cách nói lịch sự của だれ)`,
        hv: ``,
        kanji: ``,
        hira: "どなた",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ nghi vấn (lịch sự)
        en: `who (polite)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `～tuổi`,
        hv: `TUẾ`,
        kanji: `歳`,
        hira: "～さい",
        imgUrl: ``,
        pureKanji: true,
        kind: `counter`, // từ đếm
        en: `~ years old`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `mấy tuổi`,
        hv: `HÀ TUẾ`,
        kanji: `何歳`,
        hira: "なんさい",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ nghi vấn
        en: `how old`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `mấy tuổi (là cách nói lịch sự của なんさい)`,
        hv: ``,
        kanji: ``,
        hira: "おいくつ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ nghi vấn (lịch sự)
        en: `how old (polite)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Vâng, dạ`,
        hv: ``,
        kanji: ``,
        hira: "はい",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `yes`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `không`,
        hv: ``,
        kanji: ``,
        hira: "いいえ",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `no`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `xin lỗi ...`,
        hv: `THẤT LỆ`,
        kanji: `失礼ですが`,
        hira: "しつれいですが",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `Excuse me, but...`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `bạn tên gì ?`,
        hv: `DANH TIÊN`,
        kanji: `お名前は？`,
        hira: "おなまえは？",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // câu hỏi
        en: `What is your name?`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Rất hân hạnh được gặp anh/chị. (chào lần đầu)`,
        hv: `SƠ`,
        kanji: `初めまして`,
        hira: "はじめまして",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ chào hỏi
        en: `Nice to meet you (first time meeting)`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `rất hân hạnh được làm quen`,
        hv: `NGUYỄN`,
        kanji: `お願いします`,
        hira: "どうぞよろしくおねがいします",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `Please be kind to me, I look forward to working with you`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `đây là ngài ～`,
        hv: ``,
        kanji: ``,
        hira: "こちらは～さんです",
        imgUrl: ``,
        pureKanji: false,
        kind: `sentence`, // câu
        en: `This is Mr./Ms. ~`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `đến từ ～`,
        hv: ``,
        kanji: ``,
        hira: "～からきました",
        imgUrl: ``,
        pureKanji: false,
        kind: `sentence`, // câu
        en: `I came from ~ / I am from ~`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Hàn quốc`,
        hv: `HÀN QUỐC`,
        kanji: `韓国`,
        hira: "かんこく",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (quốc gia)
        en: `South Korea`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Trung Quốc`,
        hv: `TRUNG QUỐC`,
        kanji: `中国`,
        hira: "ちゅうごく",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (quốc gia)
        en: `China`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Nhật`,
        hv: `NHẬT BẢN`,
        kanji: `日本`,
        hira: "にほん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (quốc gia)
        en: `Japan`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Trường đại học Sakura`,
        hv: `ĐẠI HỌC`,
        kanji: `桜大学`,
        hira: "さくらだいがく",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (tên riêng)
        en: `Sakura University`,
    },

    // =======================
    // lesson 2
    //
    {
        level: `N5`,
        lesson: `2`,
        vn: `Đây, cái này (vật gần người nói)`,
        hv: ``,
        kanji: ``,
        hira: "これ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `this (near speaker)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Đó, cái đó (vật gần người nghe)`,
        hv: ``,
        kanji: ``,
        hira: "それ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `that (near listener)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Kia, cái kia (vật xa người nghe và nói)`,
        hv: ``,
        kanji: ``,
        hira: "あれ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `that over there (far from both)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `~này`,
        hv: ``,
        kanji: ``,
        hira: "この",
        imgUrl: ``,
        pureKanji: false,
        kind: `adjective`, // tính từ chỉ thị
        en: `this ~ (followed by noun)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `~đó`,
        hv: ``,
        kanji: ``,
        hira: "その",
        imgUrl: ``,
        pureKanji: false,
        kind: `adjective`, // tính từ chỉ thị
        en: `that ~ (followed by noun)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `~kia`,
        hv: ``,
        kanji: ``,
        hira: "あの",
        imgUrl: ``,
        pureKanji: false,
        kind: `adjective`, // tính từ chỉ thị
        en: `that ~ over there (followed by noun)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `sách`,
        hv: `BẢN`,
        kanji: `本`,
        hira: "ほん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `book`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `từ điển`,
        hv: `TỪ THƯ`,
        kanji: `辞書`,
        hira: "じしょ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `dictionary`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `tạp chí`,
        hv: `TẠP CHÍ`,
        kanji: `雑誌`,
        hira: "ざっし",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `magazine`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `báo`,
        hv: `TÂN VĂN`,
        kanji: `新聞`,
        hira: "しんぶん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `newspaper`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Vở`,
        hv: ``,
        kanji: ``,
        hira: "ノート",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `notebook`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `sổ tay`,
        hv: `THỦ TRƯỞNG`,
        kanji: `手帳`,
        hira: "てちょう",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `notebook, planner`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `danh thiếp`,
        hv: `DANH THÍCH`,
        kanji: `名刺`,
        hira: "めいし",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `business card`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Card, thẻ`,
        hv: ``,
        kanji: ``,
        hira: "カード",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `card`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Thẻ điện thoại`,
        hv: ``,
        kanji: ``,
        hira: "テレホンカード",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `telephone card`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bút chì`,
        hv: `DUYỄN BÚT`,
        kanji: `鉛筆`,
        hira: "えんびつ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `pencil`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bút bi`,
        hv: ``,
        kanji: ``,
        hira: "ボールペン",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `ballpoint pen`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bút chì kim`,
        hv: ``,
        kanji: ``,
        hira: "シャープペンシル",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `mechanical pencil`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Chìa khoá`,
        hv: ``,
        kanji: ``,
        hira: "かぎ",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ
        en: `key`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `đồng hồ`,
        hv: `THỜI KẾ`,
        kanji: `時計`,
        hira: "とけい",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `watch, clock`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Ô, dù`,
        hv: `TÁN`,
        kanji: `傘`,
        hira: "かさ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `umbrella`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `cặp sách`,
        hv: ``,
        kanji: ``,
        hira: "かばん",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ
        en: `bag, briefcase`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `máy ảnh`,
        hv: ``,
        kanji: ``,
        hira: "カメラ",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `camera`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `máy vi tính`,
        hv: ``,
        kanji: ``,
        hira: "コンピューター",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `computer`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `xe hơi, ô tô`,
        hv: `TỰ ĐỘNG XA`,
        kanji: `自動車`,
        hira: "じどうしゃ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `car, automobile`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bàn`,
        hv: `KỲ`,
        kanji: `机`,
        hira: "つくえ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `desk, table`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `ghế`,
        hv: ``,
        kanji: ``,
        hira: "いす",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ
        en: `chair`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `sốcôla`,
        hv: ``,
        kanji: ``,
        hira: "チョコレート",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `chocolate`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `cà phê`,
        hv: ``,
        kanji: ``,
        hira: "コーヒー",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `coffee`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `tiếng Anh`,
        hv: `ANH NGỮ`,
        kanji: `英語`,
        hira: "えいご",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `English language`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `tiếng Nhật`,
        hv: `NHẬT BÀN NGỮ`,
        kanji: `日本語`,
        hira: "にほんご",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `Japanese language`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `tiếng ~`,
        hv: `NGỮ`,
        kanji: `～語`,
        hira: "～ご",
        imgUrl: ``,
        pureKanji: true,
        kind: `suffix`, // hậu tố
        en: `~ language (suffix)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `cái gì`,
        hv: `HÀ`,
        kanji: `何`,
        hira: "なん",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ nghi vấn
        en: `what`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Đúng vậy`,
        hv: ``,
        kanji: ``,
        hira: "そう",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `that's right, yes`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `không phải, sai rồi`,
        hv: `VI`,
        kanji: `違います`,
        hira: "ちがいます",
        imgUrl: ``,
        pureKanji: true,
        kind: `verb`, // động từ
        en: `it's different, that's wrong`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `thế à?`,
        hv: ``,
        kanji: ``,
        hira: "そですか",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `is that so?, really?`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `à….ở (khi đề nghị hoặc suy nghĩ về vấn đề)`,
        hv: ``,
        kanji: ``,
        hira: "あのう",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `um..., well... (hesitation sound)`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `đây là chút lòng thành`,
        hv: `KHÍ TRÌ`,
        kanji: `ほんの気持ちです`,
        hira: "ほんのきもちです",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `it's just a small token of my feelings`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `xin mời`,
        hv: ``,
        kanji: ``,
        hira: "どうぞ",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `please, go ahead`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `cám ơn`,
        hv: ``,
        kanji: ``,
        hira: "どうも",
        imgUrl: ``,
        pureKanji: false,
        kind: `interjection`, // thán từ
        en: `thanks`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Xin chân thành cám ơn`,
        hv: ``,
        kanji: ``,
        hira: "[どうも]ありがとう[ございます]",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `thank you very much`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Từ nay mong được giúp đỡ`,
        hv: `THẾ THOẠI`,
        kanji: `これからお世話になります`,
        hira: "これからおせわになります",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `I look forward to your kindness from now on`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `chính tôi mới là người mong được giúp đỡ`,
        hv: ``,
        kanji: ``,
        hira: "こちらこそよろしく",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `I'm the one who should say that`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `băng (cassette)`,
        hv: ``,
        kanji: ``,
        hira: "カセットテープ",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `cassette tape`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `máy ghi âm`,
        hv: ``,
        kanji: ``,
        hira: "テープレコーダー",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `tape recorder`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `TV`,
        hv: ``,
        kanji: ``,
        hira: "テレビ",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `television`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `radio`,
        hv: ``,
        kanji: ``,
        hira: "ラジオ",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (katakana)
        en: `radio`,
    },

    // =======================
    // lesson 3
    //

    {
        level: `N5`,
        lesson: `3`,
        vn: `Chỗ này, đây`,
        hv: ``,
        kanji: ``,
        hira: "ここ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `here, this place`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Chỗ đó, đó`,
        hv: ``,
        kanji: ``,
        hira: "そこ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `there, that place (near listener)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Chỗ kia, kia`,
        hv: ``,
        kanji: ``,
        hira: "あそこ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị
        en: `over there, that place (far from both)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `đâu, chỗ nào`,
        hv: ``,
        kanji: ``,
        hira: "どこ",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ nghi vấn
        en: `where`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Phía này, đằng này, đây (lịch sự hơn ここ)`,
        hv: ``,
        kanji: ``,
        hira: "こちら",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị (lịch sự)
        en: `this way, here (polite)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Phía đó, đằng đó, đó (lịch sự hơn そこ)`,
        hv: ``,
        kanji: ``,
        hira: "そちら",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị (lịch sự)
        en: `that way, there (polite)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `đằng kia, chỗ kia, kia`,
        hv: ``,
        kanji: ``,
        hira: "あちら",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ chỉ thị (lịch sự)
        en: `that way over there (polite)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Phía nào, đằng nào, đâu`,
        hv: ``,
        kanji: ``,
        hira: "どちら",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ nghi vấn (lịch sự)
        en: `which way, where (polite)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `phòng học`,
        hv: `GIÁO THẤT`,
        kanji: `教室`,
        hira: "きょうしつ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `classroom`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `nhà ăn`,
        hv: `THỰC ĐƯỜNG`,
        kanji: `食堂`,
        hira: "しょくどう",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `cafeteria, dining hall`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `văn phòng`,
        hv: `SỰ VỤ SỞ`,
        kanji: `事務所`,
        hira: "じむしょ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `office`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `phòng họp`,
        hv: `HỘI NGHỊ THẤT`,
        kanji: `会議室`,
        hira: "かいぎしつ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `meeting room, conference room`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `quầy tiếp tân`,
        hv: `THU PHÓ`,
        kanji: `受付`,
        hira: "うけつけ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `reception desk`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `phòng`,
        hv: `BỐ ỐC`,
        kanji: `部屋`,
        hira: "へや",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `room`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `cầu thang bộ`,
        hv: `GIAI ĐOAN`,
        kanji: `階段`,
        hira: "かいだん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `stairs`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `nước`,
        hv: `QUỐC`,
        kanji: `[お]国`,
        hira: "[お]くに",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `country, homeland`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `công ty`,
        hv: `HỘI XÃ`,
        kanji: `会社`,
        hira: "かいしゃ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `company`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `nhà`,
        hv: ``,
        kanji: ``,
        hira: "うち",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ địa điểm
        en: `home, house`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Điện thoại`,
        hv: `ĐIỆN THOẠI`,
        kanji: `電話`,
        hira: "でんわ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `telephone`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `giày`,
        hv: `NGOA`,
        kanji: `靴`,
        hira: "くつ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `shoes`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `thuốc lá`,
        hv: ``,
        kanji: `煙草`,
        hira: "たばこ",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ (katakana)
        en: `tobacco, cigarette`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `quầy bán hàng`,
        hv: `MAI TRƯỜNG`,
        kanji: `売り場`,
        hira: "うりば",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `sales counter, shop`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `dưới lòng đất, tầng hầm`,
        hv: `ĐỊA HẠ`,
        kanji: `地下`,
        hira: "ちか",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `underground, basement`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Tầng thứ―`,
        hv: `GIAI`,
        kanji: `一階`,
        hira: "いっかい（いちがい）",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ địa điểm
        en: `first floor, 1st floor`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Tầng mấy`,
        hv: `HA GIAI`,
        kanji: `何階`,
        hira: "なんがい",
        imgUrl: ``,
        pureKanji: true,
        kind: `pronoun`, // đại từ nghi vấn
        en: `what floor, which floor`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `1 yên`,
        hv: `VIÊN`,
        kanji: `一円`,
        hira: "いちえん",
        imgUrl: ``,
        pureKanji: true,
        kind: `noun`, // danh từ
        en: `1 yen`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `bao nhiêu tiền`,
        hv: ``,
        kanji: ``,
        hira: "いくら",
        imgUrl: ``,
        pureKanji: false,
        kind: `pronoun`, // đại từ nghi vấn
        en: `how much (price)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `trăm`,
        hv: `BÁCH`,
        kanji: `百`,
        hira: "ひゃく",
        imgUrl: ``,
        pureKanji: true,
        kind: `counter`, // từ đếm
        en: `hundred`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `nghìn`,
        hv: `THIÊN`,
        kanji: `千`,
        hira: "せん",
        imgUrl: ``,
        pureKanji: true,
        kind: `counter`, // từ đếm
        en: `thousand`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `mười nghìn, vạn`,
        hv: `VẠN`,
        kanji: `万`,
        hira: "まん",
        imgUrl: ``,
        pureKanji: true,
        kind: `counter`, // từ đếm
        en: `ten thousand`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `xin lỗi`,
        hv: ``,
        kanji: ``,
        hira: "すみません",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `excuse me, I'm sorry`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Cách nói lịch sự của 'です'`,
        hv: ``,
        kanji: ``,
        hira: "～でございます",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `polite form of "desu" (to be)`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `xin cho xem ~`,
        hv: ``,
        kanji: ``,
        hira: "（を）みせてください",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `please show me ~`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `vậy thì, xin cho tôi (tôi lấy) cái ~`,
        hv: ``,
        kanji: ``,
        hira: "じゃ（～を）ください",
        imgUrl: ``,
        pureKanji: false,
        kind: `phrase`, // cụm từ giao tiếp
        en: `well then, please give me ~`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `tên địa danh ở Nhật`,
        hv: ``,
        kanji: ``,
        hira: "しんおおさか",
        imgUrl: ``,
        pureKanji: false,
        kind: `noun`, // danh từ (tên riêng)
        en: `Shin-Osaka (place name in Japan)`,
    },

    // =======================
    // lesson 4
    //
    {
        level: `N5`,
        lesson: `4`,
        vn: `Ngân hàng`,
        hv: `ngân hàng`,
        kanji: `銀行`,
        hira: "ぎんこう",
        imgUrl: ``,
        pureKanji: true, // cần thêm
        kind: `noun`, // danh từ
        en: `bank`,
    },
    // =======================
    // lesson 5
    //
];

// ====================================================================================

const katakanaVocab = [
    {
        level: `N5`,
        lesson: `1`,
        vn: `kỹ sư`,
        kata: `エンジニア`,
        imgUrl: ``,
        kind: `noun`, // danh từ nghề nghiệp
        en: `engineer`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Mỹ`,
        kata: `アメリカ`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `America, USA`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Anh`,
        kata: `イギリス`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `England, UK`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Ấn Độ`,
        kata: `インド`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `India`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Indonesia`,
        kata: `インドネシア`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Indonesia`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Thái Lan`,
        kata: `タイ`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Thailand`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Đức`,
        kata: `ドイツ`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Germany`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Pháp`,
        kata: `フランス`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `France`,
    },
    {
        level: `N5`,
        lesson: `1`,
        vn: `Brazil`,
        kata: `ブラジル`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Brazil`,
    },

    // =======================
    // lesson 2
    //

    {
        level: `N5`,
        lesson: `2`,
        vn: `máy ảnh`,
        kata: `カメラ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `camera`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `máy vi tính`,
        kata: `コンピューター`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `computer`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `sốcôla`,
        kata: `チョコレート`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `chocolate`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `cà phê`,
        kata: `コーヒー`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `coffee`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Vở`,
        kata: `ノート`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `notebook`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Card, thẻ`,
        kata: `カード`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `card`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `Thẻ điện thoại`,
        kata: `テレホンカード`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `telephone card`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bút bi`,
        kata: `ボールペン`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `ballpoint pen`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `bút chì kim`,
        kata: `シャープペンシル`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `mechanical pencil`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `băng (cassette)`,
        kata: `カセットテープ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `cassette tape`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `máy ghi âm`,
        kata: `テープレコーダー`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `tape recorder`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `TV`,
        kata: `テレビ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `television`,
    },
    {
        level: `N5`,
        lesson: `2`,
        vn: `radio`,
        kata: `ラジオ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `radio`,
    },

    // =======================
    // lesson 3
    //

    {
        level: `N5`,
        lesson: `3`,
        vn: `đại sảnh, hành lang`,
        kata: `ロビー`,
        imgUrl: ``,
        kind: `noun`, // danh từ địa điểm
        en: `lobby`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `nhà vệ sinh, WC`,
        kata: `トイレ`,
        imgUrl: ``,
        kind: `noun`, // danh từ địa điểm
        en: `toilet, restroom`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `thang máy`,
        kata: `エレベーター`,
        imgUrl: ``,
        kind: `noun`, // danh từ địa điểm
        en: `elevator`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `thang cuốn`,
        kata: `エスカレーター`,
        imgUrl: ``,
        kind: `noun`, // danh từ địa điểm
        en: `escalator`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `cà vạt`,
        kata: `ネクタイ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `necktie, tie`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `rượu vang`,
        kata: `ワイン`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `wine`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `thuốc lá`,
        kata: `タバコ`,
        imgUrl: ``,
        kind: `noun`, // danh từ
        en: `tobacco, cigarette`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Ý`,
        kata: `イタリア`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Italy`,
    },
    {
        level: `N5`,
        lesson: `3`,
        vn: `Thụy Sỹ`,
        kata: `スイス`,
        imgUrl: ``,
        kind: `noun`, // danh từ (quốc gia)
        en: `Switzerland`,
    },
    // =======================
    // lesson 4
    //

    // =======================
    // lesson 5
    //
];
