const vocabData = {
    n5: {
        lesson1: {
            kanji: [
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `tôi`,
                    hv: `TƯ`,
                    kanji: `私`,
                    hira: "わたし",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ
                    en: `I, me`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `chúng ta, chúng tôi`,
                    hv: ``,
                    kanji: `私たち`,
                    hira: "わたしたち",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ
                    en: `we, us`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `các bạn, các anh/chị, mọi người, quý vị`,
                    hv: `GIAI`,
                    kanji: `皆さん`,
                    hira: "みなさん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `everyone, all of you`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `bé (hậu tố thêm vào sau tên bé trai thay cho ～さん)`,
                    hv: `QUẢN`,
                    kanji: `君`,
                    hira: `くん`,
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `suffix`, // hậu tố
                    en: `(suffix for boys/juniors)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `người nước ～`,
                    hv: `NHÂN`,
                    kanji: `人`,
                    hira: `じん`,
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `suffix`, // hậu tố
                    en: `person from ~ (nationality suffix)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `giáo viên (không dùng để nói về nghề nghiệp của mình)`,
                    hv: `TIÊN SINH`,
                    kanji: `先生`,
                    hira: "せんせい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `teacher`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `giáo viên`,
                    hv: `GIÁO SƯ`,
                    kanji: `教師`,
                    hira: "きょうし",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `teacher, instructor`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `học sinh, sinh viên`,
                    hv: `HỌC SINH`,
                    kanji: `学生`,
                    hira: "がくせい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `student`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `nhân viên công ty`,
                    hv: `HỘI XÃ VIÊN`,
                    kanji: `会社員`,
                    hira: "かいしゃいん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `company employee`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `nhân viên công ty ～`,
                    hv: `XÃ VIÊN`,
                    kanji: `社員`,
                    hira: `しゃいん`,
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `~ company employee`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `nhân viên ngân hàng`,
                    hv: `NGÂN HÀNH VIÊN`,
                    kanji: `銀行員`,
                    hira: "ぎんこういん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `bank employee`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `bác sĩ`,
                    hv: `Y GIÁ`,
                    kanji: `医者`,
                    hira: "いしゃ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `doctor`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Nhà nghiên cứu`,
                    hv: `NGHIÊN CỨU GIÁ`,
                    kanji: `研究者`,
                    hira: "けんきゅうしゃ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `researcher`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `trường đại học`,
                    hv: `ĐẠI HỌC`,
                    kanji: `大学`,
                    hira: "だいがく",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `university, college`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `bệnh viện`,
                    hv: `BỆNH VIÊN`,
                    kanji: `病院`,
                    hira: "びょういん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `hospital`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `điện`,
                    hv: `DIỆN KHÍ`,
                    kanji: `電気`,
                    hira: "でんき",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `electricity, electric light`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `ai (hỏi người nào đó)`,
                    hv: `thùy`,
                    kanji: `誰`,
                    hira: "だれ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `who`,
                },

                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `～tuổi`,
                    hv: `TUẾ`,
                    kanji: `歳`,
                    hira: "さい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `counter`, // từ đếm
                    en: `~ years old`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `mấy tuổi`,
                    hv: `HÀ TUẾ`,
                    kanji: `何歳`,
                    hira: "なんさい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `how old`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Hàn quốc`,
                    hv: `HÀN QUỐC`,
                    kanji: `韓国`,
                    hira: "かんこく",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `South Korea`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Trung Quốc`,
                    hv: `TRUNG QUỐC`,
                    kanji: `中国`,
                    hira: "ちゅうごく",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `China`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Nhật`,
                    hv: `NHẬT BẢN`,
                    kanji: `日本`,
                    hira: "にほん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Japan`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Trường đại học Sakura`,
                    hv: `ĐẠI HỌC`,
                    kanji: `桜大学`,
                    hira: "さくらだいがく",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (tên riêng)
                    en: `Sakura University`,
                },
            ],
            hiragana: [
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `vị kia`,
                    hv: `PHƯƠNG`,
                    kanji: `あの方`,
                    hira: "あのかた",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (lịch sự)
                    en: `that person (polite)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `ban, anh/chị, ông/bà...`,
                    hv: ``,
                    kanji: ``,
                    hira: "あなた",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ
                    en: `you`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `người kia, người đó`,
                    hv: `NHÂN`,
                    kanji: `あの人`,
                    hira: "あのひと",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `noun`, // danh từ
                    en: `that person, he/she`,
                },

                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `anh, chị, ông, bà...`,
                    hv: ``,
                    kanji: ``,
                    hira: `～さん`,
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `suffix`, // hậu tố
                    en: `Mr./Ms. (honorific suffix)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `bé (hậu tố thêm vào sau tên bé gái thay cho ～さん)`,
                    hv: ``,
                    kanji: ``,
                    hira: `～ちゃん`,
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `suffix`, // hậu tố
                    en: `(cute suffix for girls/children)`,
                },

                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `vị nào (là cách nói lịch sự của だれ)`,
                    hv: ``,
                    kanji: ``,
                    hira: "どなた",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ nghi vấn (lịch sự)
                    en: `who (polite)`,
                },

                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `mấy tuổi (là cách nói lịch sự của なんさい)`,
                    hv: ``,
                    kanji: ``,
                    hira: "おいくつ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ nghi vấn (lịch sự)
                    en: `how old (polite)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `xin lỗi ...`,
                    hv: `THẤT LỆ`,
                    kanji: `失礼ですが`,
                    hira: "しつれいですが",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `Excuse me, but...`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `bạn tên gì ?`,
                    hv: `DANH TIÊN`,
                    kanji: `お名前は？`,
                    hira: "おなまえは？",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // câu hỏi
                    en: `What is your name?`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Rất hân hạnh được gặp anh/chị. (chào lần đầu)`,
                    hv: `SƠ`,
                    kanji: `初めまして`,
                    hira: "はじめまして",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ chào hỏi
                    en: `Nice to meet you (first time meeting)`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `đây là ngài ～`,
                    hv: ``,
                    kanji: ``,
                    hira: "こちらは～さんです",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `sentence`, // câu
                    en: `This is Mr./Ms. ~`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `đến từ ～`,
                    hv: ``,
                    kanji: ``,
                    hira: "からきました",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `sentence`, // câu
                    en: `I came from ~ / I am from ~`,
                },
            ],
            katakana: [
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `kỹ sư`,
                    kata: `エンジニア`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ nghề nghiệp
                    en: `engineer`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Mỹ`,
                    kata: `アメリカ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `America, USA`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Anh`,
                    kata: `イギリス`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `England, UK`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Ấn Độ`,
                    kata: `インド`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `India`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Indonesia`,
                    kata: `インドネシア`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Indonesia`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Thái Lan`,
                    kata: `タイ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Thailand`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Đức`,
                    kata: `ドイツ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Germany`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Pháp`,
                    kata: `フランス`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `France`,
                },
                {
                    level: `N5`,
                    lesson: `1`,
                    vi: `Brazil`,
                    kata: `ブラジル`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Brazil`,
                },
            ],
        },
        lesson2: {
            kanji: [
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `sách`,
                    hv: `BẢN`,
                    kanji: `本`,
                    hira: "ほん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `book`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `từ điển`,
                    hv: `TỪ THƯ`,
                    kanji: `辞書`,
                    hira: "じしょ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `dictionary`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `tạp chí`,
                    hv: `TẠP CHÍ`,
                    kanji: `雑誌`,
                    hira: "ざっし",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `magazine`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `báo`,
                    hv: `TÂN VĂN`,
                    kanji: `新聞`,
                    hira: "しんぶん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `newspaper`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `sổ tay`,
                    hv: `THỦ TRƯỞNG`,
                    kanji: `手帳`,
                    hira: "てちょう",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `notebook, planner`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `danh thiếp`,
                    hv: `DANH THÍCH`,
                    kanji: `名刺`,
                    hira: "めいし",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `business card`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `bút chì`,
                    hv: `DUYỄN BÚT`,
                    kanji: `鉛筆`,
                    hira: "えんびつ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `pencil`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Chìa khoá`,
                    hv: `KIỆN`,
                    kanji: `鍵`,
                    hira: "かぎ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `noun`, // danh từ
                    en: `key`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `đồng hồ`,
                    hv: `THỜI KẾ`,
                    kanji: `時計`,
                    hira: "とけい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `watch, clock`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Ô, dù`,
                    hv: `TÁN`,
                    kanji: `傘`,
                    hira: "かさ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `umbrella`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `cặp sách`,
                    hv: ``,
                    kanji: `鞄`,
                    hira: "かばん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `bag, briefcase`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `xe hơi, ô tô`,
                    hv: `TỰ ĐỘNG XA`,
                    kanji: `自動車`,
                    hira: "じどうしゃ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `car, automobile`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `bàn`,
                    hv: `KỲ`,
                    kanji: `机`,
                    hira: "つくえ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `desk, table`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `ghế`,
                    hv: ``,
                    kanji: `椅子`,
                    hira: "いす",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `chair`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `tiếng Anh`,
                    hv: `ANH NGỮ`,
                    kanji: `英語`,
                    hira: "えいご",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `English language`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `tiếng Nhật`,
                    hv: `NHẬT BÀN NGỮ`,
                    kanji: `日本語`,
                    hira: "にほんご",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `Japanese language`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `tiếng ~`,
                    hv: `NGỮ`,
                    kanji: `語`,
                    hira: "ご",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `suffix`, // hậu tố
                    en: `~ language (suffix)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `cái gì`,
                    hv: `HÀ`,
                    kanji: `何`,
                    hira: "なん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `what`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `không phải, sai rồi`,
                    hv: `VI`,
                    kanji: `違います`,
                    hira: "ちがいます",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `verb`, // động từ
                    en: `it's different, that's wrong`,
                },
            ],
            hiragana: [
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Đây, cái này (vật gần người nói)`,
                    hv: ``,
                    kanji: ``,
                    hira: "これ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `this (near speaker)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Đó, cái đó (vật gần người nghe)`,
                    hv: ``,
                    kanji: ``,
                    hira: "それ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `that (near listener)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Kia, cái kia (vật xa người nghe và nói)`,
                    hv: ``,
                    kanji: ``,
                    hira: "あれ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `that over there (far from both)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `~này`,
                    hv: ``,
                    kanji: ``,
                    hira: "この",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `adjective`, // tính từ chỉ thị
                    en: `this ~ (followed by noun)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `~đó`,
                    hv: ``,
                    kanji: ``,
                    hira: "その",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `adjective`, // tính từ chỉ thị
                    en: `that ~ (followed by noun)`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `~kia`,
                    hv: ``,
                    kanji: ``,
                    hira: "あの",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `adjective`, // tính từ chỉ thị
                    en: `that ~ over there (followed by noun)`,
                },

                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Đúng vậy`,
                    hv: ``,
                    kanji: ``,
                    hira: "そう",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `interjection`, // thán từ
                    en: `that's right, yes`,
                },

                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `thế à?`,
                    hv: ``,
                    kanji: ``,
                    hira: "そですか",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `is that so?, really?`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `đây là chút lòng thành`,
                    hv: `KHÍ TRÌ`,
                    kanji: `ほんの気持ちです`,
                    hira: "ほんのきもちです",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `it's just a small token of my feelings`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `xin mời`,
                    hv: ``,
                    kanji: ``,
                    hira: "どうぞ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `interjection`, // thán từ
                    en: `please, go ahead`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `cám ơn`,
                    hv: ``,
                    kanji: ``,
                    hira: "どうも",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `interjection`, // thán từ
                    en: `thanks`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Xin chân thành cám ơn`,
                    hv: ``,
                    kanji: ``,
                    hira: "[どうも]ありがとう[ございます]",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `thank you very much`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Từ nay mong được giúp đỡ`,
                    hv: `THẾ THOẠI`,
                    kanji: `これからお世話になります`,
                    hira: "これからおせわになります",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `I look forward to your kindness from now on`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `chính tôi mới là người mong được giúp đỡ`,
                    hv: ``,
                    kanji: ``,
                    hira: "こちらこそよろしく",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `I'm the one who should say that`,
                },
            ],
            katakana: [
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `máy ảnh`,
                    kata: `カメラ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `camera`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `máy vi tính`,
                    kata: `コンピューター`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `computer`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `sôcôla`,
                    kata: `チョコレート`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `chocolate`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `cà phê`,
                    kata: `コーヒー`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `coffee`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Vở`,
                    kata: `ノート`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `notebook`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Card, thẻ`,
                    kata: `カード`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `card`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `Thẻ điện thoại`,
                    kata: `テレホンカード`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `telephone card`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `bút bi`,
                    kata: `ボールペン`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `ballpoint pen`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `bút chì kim`,
                    kata: `シャープペンシル`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `mechanical pencil`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `băng (cassette)`,
                    kata: `カセットテープ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `cassette tape`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `máy ghi âm`,
                    kata: `テープレコーダー`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `tape recorder`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `TV`,
                    kata: `テレビ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `television`,
                },
                {
                    level: `N5`,
                    lesson: `2`,
                    vi: `radio`,
                    kata: `ラジオ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `radio`,
                },
            ],
        },
        lesson3: {
            kanji: [
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `phòng học`,
                    hv: `GIÁO THẤT`,
                    kanji: `教室`,
                    hira: "きょうしつ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `classroom`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `nhà ăn`,
                    hv: `THỰC ĐƯỜNG`,
                    kanji: `食堂`,
                    hira: "しょくどう",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `cafeteria, dining hall`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `văn phòng`,
                    hv: `SỰ VỤ SỞ`,
                    kanji: `事務所`,
                    hira: "じむしょ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `office`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `phòng họp`,
                    hv: `HỘI NGHỊ THẤT`,
                    kanji: `会議室`,
                    hira: "かいぎしつ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `meeting room, conference room`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `quầy tiếp tân`,
                    hv: `THU PHÓ`,
                    kanji: `受付`,
                    hira: "うけつけ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `reception desk`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `phòng`,
                    hv: `BỐ ỐC`,
                    kanji: `部屋`,
                    hira: "へや",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `room`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `cầu thang bộ`,
                    hv: `GIAI ĐOAN`,
                    kanji: `階段`,
                    hira: "かいだん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `stairs`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `nước`,
                    hv: `QUỐC`,
                    kanji: `お国`,
                    hira: "おくに",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `country, homeland`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `công ty`,
                    hv: `HỘI XÃ`,
                    kanji: `会社`,
                    hira: "かいしゃ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `company`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `nhà`,
                    hv: `GIA`,
                    kanji: `家`,
                    hira: "うち",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `home, house`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Điện thoại`,
                    hv: `ĐIỆN THOẠI`,
                    kanji: `電話`,
                    hira: "でんわ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `telephone`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `giày`,
                    hv: `NGOA`,
                    kanji: `靴`,
                    hira: "くつ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `shoes`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `thuốc lá`,
                    hv: `YÊN THẢO`,
                    kanji: `煙草`,
                    hira: "たばこ",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ (katakana)
                    en: `tobacco, cigarette`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `quầy bán hàng`,
                    hv: `MAI TRƯỜNG`,
                    kanji: `売り場`,
                    hira: "うりば",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `sales counter, shop`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `dưới lòng đất, tầng hầm`,
                    hv: `ĐỊA HẠ`,
                    kanji: `地下`,
                    hira: "ちか",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `underground, basement`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Tầng thứ―`,
                    hv: `GIAI`,
                    kanji: `階`,
                    hira: "かい", // かい&がい
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ địa điểm
                    en: `first floor, 1st floor`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Tầng mấy`,
                    hv: `HA GIAI`,
                    kanji: `何階`,
                    hira: "なんがい",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `what floor, which floor`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `yên`,
                    hv: `VIÊN`,
                    kanji: `円`,
                    hira: "えん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `noun`, // danh từ
                    en: `1 yen`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `bao nhiêu tiền`,
                    hv: `KI`,
                    kanji: `幾ら`,
                    hira: "いくら",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `how much (price)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `trăm`,
                    hv: `BÁCH`,
                    kanji: `百`,
                    hira: "ひゃく",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `counter`, // từ đếm
                    en: `hundred`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `nghìn`,
                    hv: `THIÊN`,
                    kanji: `千`,
                    hira: "せん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `counter`, // từ đếm
                    en: `thousand`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `mười nghìn, vạn`,
                    hv: `VẠN`,
                    kanji: `万`,
                    hira: "まん",
                    imgUrl: ``,
                    pureKanji: true,
                    kind: `counter`, // từ đếm
                    en: `ten thousand`,
                },
            ],
            hiragana: [
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Chỗ này, đây`,
                    hv: ``,
                    kanji: ``,
                    hira: "ここ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `here, this place`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Chỗ đó, đó`,
                    hv: ``,
                    kanji: ``,
                    hira: "そこ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `there, that place (near listener)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Chỗ kia, kia`,
                    hv: ``,
                    kanji: ``,
                    hira: "あそこ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị
                    en: `over there, that place (far from both)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `đâu, chỗ nào`,
                    hv: ``,
                    kanji: ``,
                    hira: "どこ",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ nghi vấn
                    en: `where`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Phía này, đằng này, đây (lịch sự hơn ここ)`,
                    hv: ``,
                    kanji: ``,
                    hira: "こちら",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị (lịch sự)
                    en: `this way, here (polite)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Phía đó, đằng đó, đó (lịch sự hơn そこ)`,
                    hv: ``,
                    kanji: ``,
                    hira: "そちら",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị (lịch sự)
                    en: `that way, there (polite)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `đằng kia, chỗ kia, kia`,
                    hv: ``,
                    kanji: ``,
                    hira: "あちら",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ chỉ thị (lịch sự)
                    en: `that way over there (polite)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Phía nào, đằng nào, đâu`,
                    hv: ``,
                    kanji: ``,
                    hira: "どちら",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `pronoun`, // đại từ nghi vấn (lịch sự)
                    en: `which way, where (polite)`,
                },

                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `xin lỗi`,
                    hv: ``,
                    kanji: ``,
                    hira: "すみません",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `excuse me, I'm sorry`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Cách nói lịch sự của 'です'`,
                    hv: ``,
                    kanji: ``,
                    hira: "でございます",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `polite form of "desu" (to be)`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `xin cho xem ~`,
                    hv: ``,
                    kanji: ``,
                    hira: "みせてください",
                    imgUrl: ``,
                    pureKanji: false,
                    kind: `phrase`, // cụm từ giao tiếp
                    en: `please show me ~`,
                },
            ],
            katakana: [
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `đại sảnh, hành lang`,
                    kata: `ロビー`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ địa điểm
                    en: `lobby`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `nhà vệ sinh, WC`,
                    kata: `トイレ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ địa điểm
                    en: `toilet, restroom`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `thang máy`,
                    kata: `エレベーター`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ địa điểm
                    en: `elevator`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `thang cuốn`,
                    kata: `エスカレーター`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ địa điểm
                    en: `escalator`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `cà vạt`,
                    kata: `ネクタイ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `necktie, tie`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `rượu vang`,
                    kata: `ワイン`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `wine`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `thuốc lá`,
                    kata: `タバコ`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ
                    en: `tobacco, cigarette`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Ý`,
                    kata: `イタリア`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Italy`,
                },
                {
                    level: `N5`,
                    lesson: `3`,
                    vi: `Thụy Sỹ`,
                    kata: `スイス`,
                    imgUrl: ``,
                    kind: `noun`, // danh từ (quốc gia)
                    en: `Switzerland`,
                },
            ],
        },
        lesson4: {
            kanji: [
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thức dậy",
                    hv: "KHỞI",
                    kanji: "起きます",
                    hira: "おきます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to wake up, to get up",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "ngủ",
                    hv: "TÂM",
                    kanji: "寝ます",
                    hira: "ねます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to sleep",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "làm việc",
                    hv: "ĐỘNG",
                    kanji: "働きます",
                    hira: "はたらきます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to work",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "nghỉ ngơi",
                    hv: "HƯU",
                    kanji: "休みます",
                    hira: "やすみます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to rest, to take a break",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "học tập",
                    hv: "MIỀN CƯỜNG",
                    kanji: "勉強します",
                    hira: "べんきょうします",
                    pureKanji: true,
                    kind: "verb",
                    en: "to study",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "kết thúc, hết",
                    hv: "CHUNG",
                    kanji: "終わります",
                    hira: "おわります",
                    pureKanji: true,
                    kind: "verb",
                    en: "to finish, to end",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "ngân hàng",
                    hv: "NGÂN HÀNH",
                    kanji: "銀行",
                    hira: "ぎんこう",
                    pureKanji: true,
                    kind: "noun",
                    en: "bank",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "bưu điện",
                    hv: "BƯU TIẾN CỤC",
                    kanji: "郵便局",
                    hira: "ゆうびんきょく",
                    pureKanji: true,
                    kind: "noun",
                    en: "post office",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thư viện",
                    hv: "ĐỒ THƯ QUẢN",
                    kanji: "図書館",
                    hira: "としょかん",
                    pureKanji: true,
                    kind: "noun",
                    en: "library",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "viện bảo tàng",
                    hv: "MỸ THUẬT QUẢN",
                    kanji: "美術館",
                    hira: "びじゅつかん",
                    pureKanji: true,
                    kind: "noun",
                    en: "art museum",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "số điện thoại",
                    hv: "ĐIỆN THOẠI PHIÊN HIỆU",
                    kanji: "電話番号",
                    hira: "でんわばんごう",
                    pureKanji: true,
                    kind: "noun",
                    en: "telephone number",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "bây giờ",
                    hv: "KIM",
                    kanji: "今",
                    hira: "いま",
                    pureKanji: true,
                    kind: "noun",
                    en: "now",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ sáu",
                    hv: "KIM DIỆU NHẬT",
                    kanji: "金曜日",
                    hira: "きんようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Friday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ bảy",
                    hv: "THỔ DIỆU NHẬT",
                    kanji: "土曜日",
                    hira: "どようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Saturday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "chủ nhật",
                    hv: "NHẬT DIỆU NHẬT",
                    kanji: "日曜日",
                    hira: "にちようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Sunday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ mấy",
                    hv: "HÀ DIỆU NHẬT",
                    kanji: "何曜日",
                    hira: "なんようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "what day of the week",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "số",
                    hv: "PHIÊN HIỆU",
                    kanji: "番号",
                    hira: "ばんごう",
                    pureKanji: true,
                    kind: "noun",
                    en: "number",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "số bao nhiêu",
                    hv: "HÀ PHIÊN",
                    kanji: "何番",
                    hira: "なんばん",
                    pureKanji: true,
                    kind: "noun",
                    en: "what number",
                },

                {
                    level: "N5",
                    lesson: "4",
                    vi: "~giờ",
                    hv: "THỜI",
                    kanji: "時",
                    hira: "じ",
                    pureKanji: false,
                    kind: "counter",
                    en: "~ o'clock",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "~phút",
                    hv: "PHẦN",
                    kanji: "～分",
                    hira: "ふん", //ふん&ぶん&ぷん
                    pureKanji: false,
                    kind: "counter",
                    en: "~ minute(s)",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "phân nửa",
                    hv: "BÁN",
                    kanji: "半",
                    hira: "はん",
                    pureKanji: true,
                    kind: "noun",
                    en: "half",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "mấy giờ",
                    hv: "HÀ THỜI",
                    kanji: "何時",
                    hira: "なんじ",
                    pureKanji: true,
                    kind: "noun",
                    en: "what time",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "mấy phút",
                    hv: "HÀ PHÂN",
                    kanji: "何分",
                    hira: "なんぷん",
                    pureKanji: true,
                    kind: "noun",
                    en: "how many minutes, what minute",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "sáng (trước 12 giờ trưa)",
                    hv: "NGỌ TIỀN",
                    kanji: "午前",
                    hira: "ごぜん",
                    pureKanji: true,
                    kind: "noun",
                    en: "AM, morning (before noon)",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "chiều (sau 12 giờ trưa)",
                    hv: "NGỌ HẬU",
                    kanji: "午後",
                    hira: "ごご",
                    pureKanji: true,
                    kind: "noun",
                    en: "PM, afternoon (after noon)",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "sáng",
                    hv: "TRIỀU",
                    kanji: "朝",
                    hira: "あさ",
                    pureKanji: true,
                    kind: "noun",
                    en: "morning",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "trưa",
                    hv: "TRÚ",
                    kanji: "昼",
                    hira: "ひる",
                    pureKanji: true,
                    kind: "noun",
                    en: "noon, daytime",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "tối",
                    hv: "VÃN",
                    kanji: "晩",
                    hira: "ばん",
                    pureKanji: true,
                    kind: "noun",
                    en: "evening, night",
                },

                {
                    level: "N5",
                    lesson: "4",
                    vi: "hôm kia",
                    hv: "NHẤT TẠC NHẬT",
                    kanji: "一昨日",
                    hira: "おととい",
                    pureKanji: true,
                    kind: "noun",
                    en: "the day before yesterday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "hôm qua",
                    hv: "TẠC NHẬT",
                    kanji: "昨日",
                    hira: "きのう",
                    pureKanji: true,
                    kind: "noun",
                    en: "yesterday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "hôm nay",
                    hv: "KIM NHẬT",
                    kanji: "今日",
                    hira: "きょう",
                    pureKanji: true,
                    kind: "noun",
                    en: "today",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "ngày mai",
                    hv: "MINH NHẬT",
                    kanji: "明日",
                    hira: "あした",
                    pureKanji: true,
                    kind: "noun",
                    en: "tomorrow",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "ngày kia",
                    hv: "MINH HẬU NHẬT",
                    kanji: "明後日",
                    hira: "あさって",
                    pureKanji: true,
                    kind: "noun",
                    en: "the day after tomorrow",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "sáng nay",
                    hv: "KIM TRIỀU",
                    kanji: "今朝",
                    hira: "けさ",
                    pureKanji: true,
                    kind: "noun",
                    en: "this morning",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "tối nay",
                    hv: "KIM VÃN",
                    kanji: "今晩",
                    hira: "こんばん",
                    pureKanji: true,
                    kind: "noun",
                    en: "this evening, tonight",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "nghỉ phép, ngày nghỉ",
                    hv: "HƯU",
                    kanji: "休み",
                    hira: "やすみ",
                    pureKanji: true,
                    kind: "noun",
                    en: "holiday, day off, break",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "nghỉ trưa",
                    hv: "TRÚ HƯU",
                    kanji: "昼休み",
                    hira: "ひるやすみ",
                    pureKanji: true,
                    kind: "noun",
                    en: "lunch break",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "mỗi sáng",
                    hv: "MỖI TRIỀU",
                    kanji: "毎朝",
                    hira: "まいあさ",
                    pureKanji: true,
                    kind: "noun",
                    en: "every morning",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "mỗi tối",
                    hv: "MỖI VÃN",
                    kanji: "毎晩",
                    hira: "まいばん",
                    pureKanji: true,
                    kind: "noun",
                    en: "every evening",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "mỗi ngày",
                    hv: "MỖI NHẬT",
                    kanji: "毎日",
                    hira: "まいにち",
                    pureKanji: true,
                    kind: "noun",
                    en: "every day",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ hai",
                    hv: "NGUYỆT DIỆU NHẬT",
                    kanji: "月曜日",
                    hira: "げつようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Monday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ ba",
                    hv: "HỎA DIỆU NHẬT",
                    kanji: "火曜日",
                    hira: "かようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Tuesday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ tư",
                    hv: "THỦY DIỆU NHẬT",
                    kanji: "水曜日",
                    hira: "すいようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Wednesday",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "thứ năm",
                    hv: "MỘC DIỆU NHẬT",
                    kanji: "木曜日",
                    hira: "もくようび",
                    pureKanji: true,
                    kind: "noun",
                    en: "Thursday",
                },
            ],
            hiragana: [
                {
                    level: "N5",
                    lesson: "4",
                    vi: "~ từ",
                    hv: "",
                    kanji: "",
                    hira: "から",
                    kind: "particle",
                    en: "from ~",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "~ đến",
                    hv: "",
                    kanji: "",
                    hira: "まで",
                    kind: "particle",
                    en: "to, until ~",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "~ và",
                    hv: "",
                    kanji: "",
                    hira: "と",
                    kind: "particle",
                    en: "and ~ (connects nouns)",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Ông/bà, phía ông/bà",
                    hv: "",
                    kanji: "",
                    hira: "そちら",
                    kind: "pronoun",
                    en: "you (polite), your side",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Anh/chị vất vả quá (bày tỏ thông cảm)",
                    hv: "ĐẠI BIẾN",
                    kanji: "大変ですね",
                    hira: "たいへんですね",
                    pureKanji: false,
                    kind: "expression",
                    en: "That's tough, isn't it? (expressing sympathy)",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Xin vui lòng giúp đỡ.",
                    hv: "NGUYỆN",
                    kanji: "お願いします",
                    hira: "おねがいします",
                    pureKanji: false,
                    kind: "expression",
                    en: "Please (do me a favor).",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Tôi hiểu rồi",
                    hv: "",
                    kanji: "",
                    hira: "かしこまりました",
                    kind: "expression",
                    en: "Certainly, I understand.",
                },
            ],
            katakana: [
                {
                    level: "N5",
                    lesson: "4",
                    vi: "cửa hàng bách hóa",
                    kata: "デパート",
                    kind: "noun",
                    en: "department store",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "New York",
                    kata: "ニューヨーク",
                    kind: "noun",
                    en: "New York",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Bắc Kinh",
                    kata: "ペキン",
                    kind: "noun",
                    en: "Beijing",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Luân Đôn",
                    kata: "ロンドン",
                    kind: "noun",
                    en: "London",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Bangkok",
                    kata: "バンコク",
                    kind: "noun",
                    en: "Bangkok",
                },
                {
                    level: "N5",
                    lesson: "4",
                    vi: "Los Angeles",
                    kata: "ロサンゼルス",
                    kind: "noun",
                    en: "Los Angeles",
                },
            ],
        },
        lesson5: {
            kanji: [
                {
                    level: "N5",
                    lesson: "5",
                    vi: "đi",
                    hv: "HÀNH",
                    kanji: "行きます",
                    hira: "いきます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to go",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "đến",
                    hv: "LAI",
                    kanji: "来ます",
                    hira: "きます",
                    pureKanji: true,
                    kind: "verb",
                    en: "to come",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "về",
                    hv: "QUY",
                    kanji: "帰ります",
                    hira: "かえります",
                    pureKanji: true,
                    kind: "verb",
                    en: "to return, to go back",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "trường học",
                    hv: "HỌC HIỆU",
                    kanji: "学校",
                    hira: "がっこう",
                    pureKanji: true,
                    kind: "noun",
                    en: "school",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "ga, nhà ga",
                    hv: "DỊCH",
                    kanji: "駅",
                    hira: "えき",
                    pureKanji: true,
                    kind: "noun",
                    en: "station",
                },

                {
                    level: "N5",
                    lesson: "5",
                    vi: "máy bay",
                    hv: "PHI HÀNH CƠ",
                    kanji: "飛行機",
                    hira: "ひこうき",
                    pureKanji: true,
                    kind: "noun",
                    en: "airplane",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "thuyền, tàu thủy",
                    hv: "THUYỀN",
                    kanji: "船",
                    hira: "ふね",
                    pureKanji: true,
                    kind: "noun",
                    en: "ship, boat",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu điện",
                    hv: "ĐIỆN XA",
                    kanji: "電車",
                    hira: "でんしゃ",
                    pureKanji: true,
                    kind: "noun",
                    en: "train, electric train",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu điện ngầm",
                    hv: "ĐỊA HẠ THIẾT",
                    kanji: "地下鉄",
                    hira: "ちかてつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "subway, underground railway",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu Shinkansen (tàu điện siêu tốc của Nhật)",
                    hv: "TÂN CÁN TUYẾN",
                    kanji: "新幹線",
                    hira: "しんかんせん",
                    pureKanji: true,
                    kind: "noun",
                    en: "Shinkansen (bullet train)",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "xe đạp",
                    hv: "TỰ CHUYỂN XA",
                    kanji: "自転車",
                    hira: "じてんしゃ",
                    pureKanji: true,
                    kind: "noun",
                    en: "bicycle",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "đi bộ",
                    hv: "BỘ",
                    kanji: "歩いて",
                    hira: "あるいて",
                    pureKanji: false,
                    kind: "verb",
                    en: "to walk",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "người",
                    hv: "NHÂN",
                    kanji: "人",
                    hira: "ひと",
                    pureKanji: true,
                    kind: "noun",
                    en: "person",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "bạn, bạn bè",
                    hv: "HỮU ĐẠT",
                    kanji: "友達",
                    hira: "ともだち",
                    pureKanji: true,
                    kind: "noun",
                    en: "friend",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "anh ấy, bạn trai",
                    hv: "BỈ",
                    kanji: "彼",
                    hira: "かれ",
                    pureKanji: true,
                    kind: "noun",
                    en: "he, boyfriend",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "chị ấy, bạn gái",
                    hv: "BỈ NỮ",
                    kanji: "彼女",
                    hira: "かのじょ",
                    pureKanji: true,
                    kind: "noun",
                    en: "she, girlfriend",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "gia đình",
                    hv: "GIA TỘC",
                    kanji: "家族",
                    hira: "かぞく",
                    pureKanji: true,
                    kind: "noun",
                    en: "family",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tuần trước",
                    hv: "TIÊN CHU",
                    kanji: "先週",
                    hira: "せんしゅう",
                    pureKanji: true,
                    kind: "noun",
                    en: "last week",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tuần này",
                    hv: "KIM CHU",
                    kanji: "今週",
                    hira: "こんしゅう",
                    pureKanji: true,
                    kind: "noun",
                    en: "this week",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tuần sau",
                    hv: "LAI CHU",
                    kanji: "来週",
                    hira: "らいしゅう",
                    pureKanji: true,
                    kind: "noun",
                    en: "next week",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tháng trước",
                    hv: "TIÊN NGUYỆT",
                    kanji: "先月",
                    hira: "せんげつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "last month",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tháng này",
                    hv: "KIM NGUYỆT",
                    kanji: "今月",
                    hira: "こんげつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "this month",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tháng sau",
                    hv: "LAI NGUYỆT",
                    kanji: "来月",
                    hira: "らいげつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "next month",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "năm ngoái",
                    hv: "KHỨ NIÊN",
                    kanji: "去年",
                    hira: "きょねん",
                    pureKanji: true,
                    kind: "noun",
                    en: "last year",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "Sân ga số ...",
                    hv: "NHẤT PHIẾN TUYẾN",
                    kanji: "番線",
                    hira: "ばんせん",
                    pureKanji: true,
                    kind: "noun",
                    en: "platform number ...",
                },

                {
                    level: "N5",
                    lesson: "5",
                    vi: "tiếp theo",
                    hv: "THỨ",
                    kanji: "次の",
                    hira: "つぎの",
                    pureKanji: true,
                    kind: "adjective",
                    en: "next",
                },

                {
                    level: "N5",
                    lesson: "5",
                    vi: "sinh nhật",
                    hv: "BÀN SINH NHẬT",
                    kanji: "誕生日",
                    hira: "たんじょうび",
                    pureKanji: true,
                    kind: "noun",
                    en: "birthday",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu thường (dừng cả ở các ga lẻ)",
                    hv: "PHỔ THÔNG",
                    kanji: "普通",
                    hira: "ふつう",
                    pureKanji: true,
                    kind: "noun",
                    en: "local train (stops at every station)",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu tốc hành",
                    hv: "CẤP HÀNH",
                    kanji: "急行",
                    hira: "きゅうこう",
                    pureKanji: true,
                    kind: "noun",
                    en: "express train",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tàu tốc hành đặc biệt",
                    hv: "ĐẶC CẤP",
                    kanji: "特急",
                    hira: "とっきゅう",
                    pureKanji: true,
                    kind: "noun",
                    en: "limited express train",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "năm nay",
                    hv: "KIM NIÊN",
                    kanji: "今年",
                    hira: "ことし",
                    pureKanji: true,
                    kind: "noun",
                    en: "this year",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "năm sau",
                    hv: "LAI NIÊN",
                    kanji: "来年",
                    hira: "らいねん",
                    pureKanji: true,
                    kind: "noun",
                    en: "next year",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tháng 1",
                    hv: "NHẤT NGUYỆT",
                    kanji: "一月",
                    hira: "いちがつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "January",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tháng mấy",
                    hv: "HÀ NGUYỆT",
                    kanji: "何月",
                    hira: "なんがつ",
                    pureKanji: true,
                    kind: "noun",
                    en: "what month",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "trường học",
                    hv: "HỌC HIỆU",
                    kanji: "学校",
                    hira: "がっこう",
                    pureKanji: true,
                    kind: "noun",
                    en: "school",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "ga, nhà ga",
                    hv: "DỊCH",
                    kanji: "駅",
                    hira: "えき",
                    pureKanji: true,
                    kind: "noun",
                    en: "station",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "ngày mấy, ngày bao nhiêu, mấy ngày, bao nhiêu ngày",
                    hv: "HÀ NHẬT",
                    kanji: "何日",
                    hira: "なんにち",
                    pureKanji: true,
                    kind: "noun",
                    en: "what day, what date, how many days",
                },
            ],
            hiragana: [
                {
                    level: "N5",
                    lesson: "5",
                    vi: "bao giờ, khi nào",
                    hv: "",
                    kanji: "",
                    hira: "いつ",
                    kind: "adverb",
                    en: "when",
                },

                {
                    level: "N5",
                    lesson: "5",
                    vi: "Không có gì",
                    hv: "",
                    kanji: "",
                    hira: "どういたしまして",
                    kind: "expression",
                    en: "You're welcome",
                },
            ],
            katakana: [
                {
                    level: "N5",
                    lesson: "5",
                    vi: "xe buýt",
                    kata: "バス",
                    kind: "noun",
                    en: "bus",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "tắc-xi",
                    kata: "タクシー",
                    kind: "noun",
                    en: "taxi",
                },
                {
                    level: "N5",
                    lesson: "5",
                    vi: "siêu thị",
                    kata: "スーパー",
                    kind: "noun",
                    en: "supermarket",
                },
            ],
        },
    },
};
